changelog:
  exclude:
    authors:
      - allcontributors
    labels:
      - release-ignore

  categories:
    - title: Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Uncategorized changes
      labels:
        - "*"
